from __future__ import annotations

from pathlib import Path
from typing import Any

from core.utils import write_text


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Write a markdown summary for the baseline phase."""
    report_path = Path(report_path)
    lines = [
        "# Phase 1 Baseline Report",
        "",
        "## Source Summary",
        f"- Source API: {source_summary.get('source_api', 'n/a')}",
        f"- Query: {source_summary.get('source_query', 'n/a')}",
        f"- Raw records fetched: {source_summary.get('raw_records_count', 0)}",
        f"- Clean rows stored: {source_summary.get('clean_rows', 0)}",
        f"- Collection name: {source_summary.get('collection_name', 'n/a')}",
        f"- Evaluation questions: {source_summary.get('test_set_size', 0)}",
        "",
        "## Retrieval and Evaluation Metrics",
        f"- Retrieval hit rate: {metrics.get('retrieval_hit_rate', 0):.3f}",
        f"- Mean token F1: {metrics.get('mean_token_f1', 0):.3f}",
        f"- Judge accuracy: {metrics.get('judge_accuracy', 0):.3f}",
        f"- Mean judge score: {metrics.get('mean_judge_score', 0):.3f}",
        "",
        "## Data Quality",
        f"- Row count: {quality.get('row_count', 0)}",
        f"- Completeness (paper_id/title/summary): {quality.get('completeness', {})}",
        f"- Uniqueness: {quality.get('uniqueness', {})}",
        "",
        "## Freshness",
        f"- Latest published date: {freshness.get('latest_published', 'n/a')}",
        f"- Oldest published date: {freshness.get('oldest_published', 'n/a')}",
        f"- Stale rows: {freshness.get('stale_rows', 0)}",
        f"- Freshness status: {'fresh' if freshness.get('is_fresh') else 'needs attention'}",
        "",
        "This report was generated by the baseline retrieval and evaluation pipeline.",
    ]
    write_text(report_path, "\n".join(lines) + "\n")


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """Write a markdown report comparing baseline, corrupted, and repaired results."""
    report_path = Path(report_path)
    
    def format_metric(b, c, r, name):
        try:
            b_val = float(b.get(name, 0))
            c_val = float(c.get(name, 0))
            r_val = float(r.get(name, 0))
            c_delta = c_val - b_val
            r_delta = r_val - b_val
            
            if (b_val - c_val) != 0:
                rec = (r_val - c_val) / (b_val - c_val)
                rec_str = f"{rec:.2%}"
            else:
                rec_str = "N/A"
                
            return f"| {name} | {b_val:.3f} | {c_val:.3f} | {r_val:.3f} | {c_delta:+.3f} | {r_delta:+.3f} | {rec_str} |"
        except Exception:
            return f"| {name} | N/A | N/A | N/A | N/A | N/A | N/A |"

    lines = [
        "# Corruption Comparison Report",
        "",
        "## RAG Evaluation Comparison",
        "| Metric | Baseline | Corrupted | Repaired | Corrupted Δ | Repaired Δ | Recovery |",
        "|---|---:|---:|---:|---:|---:|---:|",
        format_metric(baseline_metrics, corrupted_metrics, repaired_metrics, "retrieval_hit_rate"),
        format_metric(baseline_metrics, corrupted_metrics, repaired_metrics, "mean_token_f1"),
        format_metric(baseline_metrics, corrupted_metrics, repaired_metrics, "judge_accuracy"),
        format_metric(baseline_metrics, corrupted_metrics, repaired_metrics, "mean_judge_score"),
        "",
        "## Data Quality Comparison",
        "### Row count",
        f"- Corrupted: {corrupted_quality.get('row_count', 'N/A')}",
        f"- Repaired: {repaired_quality.get('row_count', 'N/A')}",
        "",
        "### Freshness Status",
        f"- Corrupted: {'fresh' if corrupted_freshness.get('is_fresh') else 'needs attention'} (Stale rows: {corrupted_freshness.get('stale_rows', 0)})",
        f"- Repaired: {'fresh' if repaired_freshness.get('is_fresh') else 'needs attention'} (Stale rows: {repaired_freshness.get('stale_rows', 0)})",
        "",
        "## Detailed Quality Notes",
        "**Corrupted Quality:**",
        f"```json\n{corrupted_quality}\n```",
        "",
        "**Repaired Quality:**",
        f"```json\n{repaired_quality}\n```",
    ]
    write_text(report_path, "\n".join(lines) + "\n")

