from __future__ import annotations

from pathlib import Path
from typing import Any

from core.utils import write_text


def generate_phase1_report(report_path, source_summary: dict[str, Any], metrics: dict[str, Any], quality: dict[str, Any], freshness: dict[str, Any]) -> None:
    lines = [
        "# Phase 1 Baseline Report", "", "## Source Summary",
        f"- Source API: {source_summary.get('source_api', 'n/a')}",
        f"- Query: {source_summary.get('source_query', 'n/a')}",
        f"- Raw records fetched: {source_summary.get('raw_records_count', 0)}",
        f"- Clean rows stored: {source_summary.get('clean_rows', 0)}",
        f"- Collection name: {source_summary.get('collection_name', 'n/a')}",
        f"- Evaluation questions: {source_summary.get('test_set_size', 0)}", "",
        "## Retrieval and Evaluation Metrics",
        f"- Retrieval hit rate: {metrics.get('retrieval_hit_rate', 0):.3f}",
        f"- Mean token F1: {metrics.get('mean_token_f1', 0):.3f}",
        f"- Judge accuracy: {metrics.get('judge_accuracy', 0):.3f}",
        f"- Mean judge score: {metrics.get('mean_judge_score', 0):.3f}", "",
        "## Data Quality", f"- Row count: {quality.get('row_count', 0)}",
        f"- Completeness (paper_id/title/summary): {quality.get('completeness', {})}",
        f"- Uniqueness: {quality.get('uniqueness', {})}", "", "## Freshness",
        f"- Latest published date: {freshness.get('latest_published', 'n/a')}",
        f"- Oldest published date: {freshness.get('oldest_published', 'n/a')}",
        f"- Stale rows: {freshness.get('stale_rows', 0)}",
        f"- Freshness status: {'fresh' if freshness.get('is_fresh') else 'needs attention'}", "",
        "This report was generated by the baseline retrieval and evaluation pipeline.",
    ]
    write_text(Path(report_path), "\n".join(lines) + "\n")


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any], corrupted_metrics: dict[str, Any], repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any], repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any], repaired_freshness: dict[str, Any],
) -> None:
    def metric(row: dict[str, Any], key: str) -> str:
        return f"{float(row.get(key, 0)):.3f}"

    baseline_quality_path = Path(report_path).parents[1] / "quality" / "baseline_quality.json"
    baseline_quality: dict[str, Any] = {}
    if baseline_quality_path.exists():
        import json
        baseline_quality = json.loads(baseline_quality_path.read_text(encoding="utf-8"))

    lines = [
        "# Corruption, Repair & Comparison Report", "",
        "## Three-state comparison", "",
        "| Metric / signal | Baseline | Corrupted | Repaired |",
        "|---|---:|---:|---:|",
        f"| Retrieval hit rate | {metric(baseline_metrics, 'retrieval_hit_rate')} | {metric(corrupted_metrics, 'retrieval_hit_rate')} | {metric(repaired_metrics, 'retrieval_hit_rate')} |",
        f"| Mean token F1 | {metric(baseline_metrics, 'mean_token_f1')} | {metric(corrupted_metrics, 'mean_token_f1')} | {metric(repaired_metrics, 'mean_token_f1')} |",
        f"| Judge accuracy | {metric(baseline_metrics, 'judge_accuracy')} | {metric(corrupted_metrics, 'judge_accuracy')} | {metric(repaired_metrics, 'judge_accuracy')} |",
        f"| Mean judge score | {metric(baseline_metrics, 'mean_judge_score')} | {metric(corrupted_metrics, 'mean_judge_score')} | {metric(repaired_metrics, 'mean_judge_score')} |",
        f"| Quality status | {baseline_quality.get('status', 'PASS')} | {corrupted_quality.get('status', 'FAIL')} | {repaired_quality.get('status', 'PASS')} |",
        f"| Duplicate paper IDs | {baseline_quality.get('uniqueness', {}).get('duplicate_paper_ids', 0)} | {corrupted_quality.get('uniqueness', {}).get('duplicate_paper_ids', 0)} | {repaired_quality.get('uniqueness', {}).get('duplicate_paper_ids', 0)} |",
        f"| Stale rows | {baseline_quality.get('freshness', {}).get('stale_rows', 0)} | {corrupted_freshness.get('stale_rows', 0)} | {repaired_freshness.get('stale_rows', 0)} |",
        f"| Freshness | {'PASS' if baseline_quality.get('freshness', {}).get('is_fresh', True) else 'FAIL'} | {'PASS' if corrupted_freshness.get('is_fresh') else 'FAIL'} | {'PASS' if repaired_freshness.get('is_fresh') else 'FAIL'} |",
        "", "## Findings", "",
        "Removing frozen-test documents has the strongest retrieval impact because the relevant evidence is absent from the index; noise and blank summaries further weaken semantic matching and answer content.",
        "", "Repair is rebuilt from the saved raw C2 snapshot so all three states use the same immutable source population. Fetching the API again could return changed records or dates, introducing dataset drift and making the comparison non-reproducible.",
    ]
    write_text(Path(report_path), "\n".join(lines) + "\n")
