from __future__ import annotations

from pathlib import Path
from typing import Any

from core.utils import write_text


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Write a markdown summary for the baseline phase."""
    report_path = Path(report_path)
    lines = [
        "# Phase 1 Baseline Report",
        "",
        "## Source Summary",
        f"- Source API: {source_summary.get('source_api', 'n/a')}",
        f"- Query: {source_summary.get('source_query', 'n/a')}",
        f"- Raw records fetched: {source_summary.get('raw_records_count', 0)}",
        f"- Clean rows stored: {source_summary.get('clean_rows', 0)}",
        f"- Collection name: {source_summary.get('collection_name', 'n/a')}",
        f"- Evaluation questions: {source_summary.get('test_set_size', 0)}",
        "",
        "## Retrieval and Evaluation Metrics",
        f"- Retrieval hit rate: {metrics.get('retrieval_hit_rate', 0):.3f}",
        f"- Mean token F1: {metrics.get('mean_token_f1', 0):.3f}",
        f"- Judge accuracy: {metrics.get('judge_accuracy', 0):.3f}",
        f"- Mean judge score: {metrics.get('mean_judge_score', 0):.3f}",
        "",
        "## Data Quality",
        f"- Row count: {quality.get('row_count', 0)}",
        f"- Completeness (paper_id/title/summary): {quality.get('completeness', {})}",
        f"- Uniqueness: {quality.get('uniqueness', {})}",
        "",
        "## Freshness",
        f"- Latest published date: {freshness.get('latest_published', 'n/a')}",
        f"- Oldest published date: {freshness.get('oldest_published', 'n/a')}",
        f"- Stale rows: {freshness.get('stale_rows', 0)}",
        f"- Freshness status: {'fresh' if freshness.get('is_fresh') else 'needs attention'}",
        "",
        "This report was generated by the baseline retrieval and evaluation pipeline.",
    ]
    write_text(report_path, "\n".join(lines) + "\n")


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """Write a markdown report comparing baseline, corrupted, and repaired results."""
    report_path = Path(report_path)
    lines = [
        "# Corruption Comparison Report",
        "",
        "## Baseline",
        f"- Retrieval hit rate: {baseline_metrics.get('retrieval_hit_rate', 0):.3f}",
        f"- Mean token F1: {baseline_metrics.get('mean_token_f1', 0):.3f}",
        "",
        "## Corrupted",
        f"- Retrieval hit rate: {corrupted_metrics.get('retrieval_hit_rate', 0):.3f}",
        f"- Mean token F1: {corrupted_metrics.get('mean_token_f1', 0):.3f}",
        f"- Freshness status: {'fresh' if corrupted_freshness.get('is_fresh') else 'needs attention'}",
        "",
        "## Repaired",
        f"- Retrieval hit rate: {repaired_metrics.get('retrieval_hit_rate', 0):.3f}",
        f"- Mean token F1: {repaired_metrics.get('mean_token_f1', 0):.3f}",
        f"- Freshness status: {'fresh' if repaired_freshness.get('is_fresh') else 'needs attention'}",
        "",
        "## Quality Notes",
        f"- Corrupted quality: {corrupted_quality}",
        f"- Repaired quality: {repaired_quality}",
    ]
    write_text(report_path, "\n".join(lines) + "\n")
